algoritmo "semnome"
var

   altura, largura, area,pintura: real

inicio

      escreva("Qual é a altura da parede? ")
      leia(altura)
      escreva("Qual a largura da parede?")
      leia(largura)
      area<- largura* altura
      pintura <- area * 2
      escreval("A area a ser pintada será : " , area , " metros")
      escreval("E ira usar : " , pintura , " litros de tinta ")
      

fimalgoritmo